# Generated by Django 5.1.5 on 2025-01-28 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_categoria_producto_fecha_publicacion_producto_foto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='logotipo',
            field=models.ImageField(blank=True, null=True, upload_to='proveedores/logos/'),
        ),
    ]
