# Generated by Django 5.1.5 on 2025-02-06 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_proveedor_logotipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='categorias/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='productos/productos/fotos'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='logotipo',
            field=models.ImageField(blank=True, null=True, upload_to='productos/proveedores/logos/'),
        ),
    ]
