# Generated by Django 5.1.4 on 2025-01-08 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_proveedor_rename_nombre_producto_nombre_producto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='nombre_producto',
            new_name='nombre_Producto',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='nombre_proveedor',
            new_name='nombre_Proveedor',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='proveedor',
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(default='Valor por defecto', on_delete=django.db.models.deletion.CASCADE, to='compras.proveedor'),
            preserve_default=False,
        ),
    ]
