# Generated by Django 5.1.4 on 2025-01-22 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0007_remove_producto_proveedor_producto_proveedores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='proveedores',
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='compras.proveedor'),
            preserve_default=False,
        ),
    ]
