# Generated by Django 5.1.4 on 2025-01-08 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_rename_nombre_producto_producto_nombre_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='compras.proveedor'),
        ),
    ]
