# Generated by Django 5.1.4 on 2025-01-22 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_rename_nombre_proveedor_proveedor_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='proveedor',
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedores',
            field=models.ManyToManyField(to='compras.proveedor'),
        ),
    ]
