# Generated by Django 5.1.5 on 2025-01-24 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0008_remove_producto_proveedores_producto_proveedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='proveedor',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
    ]
